name       : beignet
version    : 1.3.2
release    : 17
source     :
    - git|https://github.com/intel/beignet.git : fc5f430cb7b7a8f694d86acbb038bd5b38ec389c
license    : LGPL-2.1-or-later
component  : xorg.display
summary    : Intel OpenCL Implementation
description: |
    Intel OpenCL implementation
builddeps  :
    - pkgconfig(libdrm_intel)
    - pkgconfig(libva)
    - pkgconfig(OpenCL)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - llvm-clang-devel
    - llvm-devel
rundeps    :
    - devel :
        - opencl-headers
        - opencl-clhpp
setup      : |
    # Patch for newer LLVM
    git revert -n 9b7ca443cf7b 9cb7ff4c285d
    %patch -p1 < $pkgfiles/llvm8.patch
    %patch -p1 < $pkgfiles/llvm9.patch
    %patch -p1 < $pkgfiles/llvm10.patch

    # Put OCL vendor file in right place
    sed -i 's:/etc:/usr/share:' CMakeLists.txt
    mkdir build && pushd build
    %cmake -DCMAKE_BUILD_TYPE=RELEASE ..
build      : |
    %make -C build
install    : |
    %make_install -C build

    # Provided by opencl-headers
    find $installdir/usr/include/CL/ -not -name "cl_intel.h" -type f -print -delete
