name       : beignet
version    : 1.3.2
release    : 12
source     :
    - git|https://anongit.freedesktop.org/git/beignet.git : fc5f430cb7b7a8f694d86acbb038bd5b38ec389c
license    : LGPL-2.1-or-later
component  : xorg.display
summary    : Intel OpenCL Implementation
description: |
    Intel OpenCL implementation
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdrm_intel)
    - pkgconfig(libva)
    - pkgconfig(OpenCL)
    - pkgconfig(x11)
    - llvm-clang-devel
    - llvm-devel
rundeps    :
    - devel : opencl-headers
setup      : |
    # Patch for LLVM 8
    git revert -n 9b7ca443cf7b 9cb7ff4c285d
    %patch -p0 < $pkgfiles/llvm8.patch

    # Put OCL vendor file in right place
    sed -i 's:/etc:/usr/share:' CMakeLists.txt
    mkdir buildage && pushd buildage
    %cmake ..
build      : |
    %make -C buildage
install    : |
    %make_install -C buildage

    # Provided by opencl-headers
    find $installdir/usr/include/CL/ -not -name "cl_intel.h" -type f -print -delete
