name       : beignet
version    : 1.3.1
release    : 7
source     :
    - git|https://anongit.freedesktop.org/git/beignet.git : 6804cca263edd11fd03b2d7f5b7ba034d9a013c3
license    : LGPL-2.1
component  : xorg.display
summary    : Intel OpenCL Implementation
description: |
    Intel OpenCL implementation
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdrm_intel)
    - pkgconfig(libva)
    - pkgconfig(OpenCL)
    - pkgconfig(x11)
    - llvm-clang-devel
    - llvm-devel
setup      : |
    # Put OCL vendor file in right place
    sed -i 's:/etc:/usr/share:' CMakeLists.txt
    mkdir buildage && pushd buildage
    %cmake ..
build      : |
    pushd buildage
    %make
install    : |
    pushd buildage
    %make_install
