name       : beignet
version    : 1.2.0
release    : 3
source     :
    - https://git.solus-project.com/projects/beignet/snapshot/beignet-e3114dcc404d2bbd56e46291155784f7c731b17f.tar.gz : b332828affb713b8f6febed7acc7302288b125d8ef6e8c918b32857b05bc8ae8
license    : LGPL-2.1
component  : xorg.display
summary    : Intel OpenCL Implementation
description: |
    Intel OpenCL implementation
patterns   :
    - devel : /usr/lib64/beignet/include
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdrm_intel)
    - pkgconfig(libva)
    - pkgconfig(OpenCL)
    - pkgconfig(x11)
    - clang
    - clang-devel
    - llvm-devel
setup      : |
    mkdir buildage && pushd buildage
    %cmake ..
build      : |
    pushd buildage
    %make
install    : |
    pushd buildage
    %make_install
