name       : beignet
version    : 1.3.2
release    : 9
source     :
    - https://01.org/sites/default/files/beignet-1.3.2-source.tar.gz : c555edba149de23243965a703f39f79fa06f15bcff5a3762b5544b0925010b43
license    : LGPL-2.1
component  : xorg.display
summary    : Intel OpenCL Implementation
description: |
    Intel OpenCL implementation
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdrm_intel)
    - pkgconfig(libva)
    - pkgconfig(OpenCL)
    - pkgconfig(x11)
    - llvm-clang-devel
    - llvm-devel
rundeps    :
    - devel : opencl-headers
setup      : |
    # Put OCL vendor file in right place
    sed -i 's:/etc:/usr/share:' CMakeLists.txt
    mkdir buildage && pushd buildage
    %cmake ..
build      : |
    %make -C buildage
install    : |
    %make_install -C buildage

    # Provided by opencl-headers
    find $installdir/usr/include/CL/ -not -name "cl_intel.h" -type f -print -delete

