name       : beignet
version    : 1.2.0
release    : 2
source     :
    - https://git.solus-project.com/projects/beignet/snapshot/beignet-1.2.0-solus.tar.gz : dc97d7b9fdec26306325bdf634514688433e58a590a76684f82620c5090e3bb4
license    : LGPL-2.1
component  : xorg.display
summary    : Intel OpenCL Implementation
description: |
    Intel OpenCL implementation
patterns   :
    - devel : /usr/lib64/beignet/include
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdrm_intel)
    - pkgconfig(libva)
    - pkgconfig(OpenCL)
    - pkgconfig(x11)
    - clang
    - clang-devel
    - llvm-devel
setup      : |
    mkdir buildage && pushd buildage
    %cmake ..
build      : |
    pushd buildage
    %make
install    : |
    pushd buildage
    %make_install
